[theme]
base = "light"
primaryColor = "#027373"
backgroundColor = "#F2E7DC"
secondaryBackgroundColor = "#A9D9D0"
textColor = "#0D0D0D"
font = "monospace"
[server]
fileWatcherType = "none"   # 파일 생성/갱신 시 재실행 방지 (인코딩 중 튕김 예방)
